spring:
  profiles:
    active: test
  devtools:
    livereload:
      enable: true
    restart:
      enable: true

  thymeleaf:
    cache: false

  session:
    jdbc.initialize-schema: always

  messages:
    basename: messages,ValidationMessages,PropertyNames
    cache-duration: -1
    encoding: UTF-8

server:
  servlet:
    session:
      timeout: 60m
  ssl:
    key-store: keystore.p12
    key-store-password: itzon1234
  error:
    whitelabel:
      enabled: false

---
spring:
  profiles: test
  cache:
    type: NONE
  datasource:
    url: jdbc:mariadb://211.44.183.197:3308/home?zeroDateTimeBehavior=convertToNull
    username: itzon
    password: itzon12345
    driver-class-name: org.mariadb.jdbc.Driver
    driver: org.mariadb.jdbc.Driver
    hikari:
      max-lifetime: 30000
      idle-timeout: 10000
  exposed:
    generate-ddl: true
#  jpa:
#    hibernate:
#      ddl-auto: none

logging:
  level:
    Exposed: debug


server:
  port: 443
  ssl:
    enabled: true

cti:
  klcns:
    url: 124.139.166.173
    #    url: 211.253.38.136
    port: 18088

port:
  http: 80
  https: 443

itzon:
  server:
    url: 211.44.183.197
    port: 443
    sample:
      url: 1.2.3.4
      port: 2020
  sftp:
    url: 211.44.183.197
    port: 22
    id: itzon
    password: itzon1234!0
    defaultpath : /root/file/share
  book:
    defaultpath : /root/file/book
---
---
spring:
  profiles: local
  cache:
    type: NONE
  datasource:
    url: jdbc:mariadb://211.44.183.197:3308/home?zeroDateTimeBehavior=convertToNull
    username: itzon
    password: itzon12345
    driver-class-name: org.mariadb.jdbc.Driver
    driver: org.mariadb.jdbc.Driver
    hikari:
      max-lifetime: 30000
      idle-timeout: 10000
  exposed:
    generate-ddl: true
#  jpa:
#    hibernate:
#      ddl-auto: none

logging:
  level:
    Exposed: debug

server:
  port: 8104
  ssl:
    enabled: false

cti:
  klcns:
    url: 124.139.166.173
    #    url: 211.253.38.136
    port: 18088

port:
  http: 8103
  https: 8104

itzon:
  server:
    url: 211.44.183.197
    port: 443
    sample:
      url: 1.2.3.4
      port: 2020
  sftp:
    url: 211.44.183.197
    port: 22
    id: itzon
    password: itzon1234!0
    defaultpath : /root/file/share
  book:
    defaultpath: C:\Users\jws70\OneDrive\바탕 화면\book
---